secret-54 major changes to database and fixes
saltybots/secretsalty-backend-j pull request #3
Opened 2024-04-28 17:13 UTC by ZleMyzteX

* changed / fixed database schema
* added basic architecture tests
* update dependencies
* added lombok

2024-04-30 09:24 UTC, leakonvalinka requested changes
vl sollte man die controller rausnehmen? die sollen ja dann die andern schreiben
bevor mans auf main schallert

2024-04-30 09:30 UTC, leakonvalinka commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/UserRepository.java
> +    public User update(User newUser) {
das setzt nur values von registered users, also guest update fehlt noch (falls das möglich sein soll? kann man überlegen ob man das braucht)

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/endpoint/controller/UserController.java
> +    System.out.println("creating new user: " + newUser);
if we want to log stuff (temporarily, even) we should use a logger
-> here I'd suggest to simply use the @log4j annotation & put a log.debug("...", newUser) into this.

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/GroupRepository.java
>    public Group readById(UUID uuid) {
we should change the name back to UUID, readById is wrong at the moment

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/GroupRepository.java
> +        .fetchOneInto(Group.class);
nice

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/ParticipantRepository.java
> +  public List<Participant> readAllForUser(UUID userUuid) {
I'd maybe change the name here; readAllForUser is a little bit confusing?

readAllByUser maybe? 🤔

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/ParticipantRepository.java
> +    // participantRecord.setBengerlUuid(participant.getBengerlUuid());
why is this commented out? 

and maybe we should really switch to mapstruct or something similar

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/UserRepository.java
> +    LocalDateTime now = LocalDateTime.now();
we should maybe put this into a LocalDateTimeUtil class or something like that to share that logic

2024-05-26 13:40 UTC, ZleMyzteX commented on SecretSalty/src/main/java/com/secretsalty/secretsalty/repository/UserRepository.java
> +    return user;
can simply return, no assignment needed here

2024-05-26 14:12 UTC, merged